language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
sudo: required
install:
- pip install pip==9.0.3
- pip install pytest pytest-cov
- pip install yapf==0.20.0
- pip install coveralls
- pip install urllib3==1.23
- pip install chardet==3.0.2
- pip install requests==2.19.1
- python setup.py install
script:
- pytest --cov-config .coveragerc --cov=datmo -s -v
- echo $TRAVIS_COMMIT_RANGE
- bash devtools/travis-ci/test_format_code.sh
after_success:
- echo $TRAVIS_SECURE_ENV_VARS
- coveralls
env:
  global:
    - LOGGING_LEVEL=DEBUG
    - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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
    - DATMO_API_KEY=6a3a3cd900eaf7b406a41d68f8ca7969
