language: python
python:
- '2.7'
- '3.5'
sudo: required
dist: trusty
install:
- pip install pytest pytest-cov
- pip install coveralls
- python setup.py install
script:
- pytest --cov-config .coveragerc --cov=datmo
after_script:
- echo $TRAVIS_SECURE_ENV_VARS
- coveralls