language: python
python:
- '2.7'
- '3.5'
sudo: required
dist: trusty
install:
- pip install coveralls
- python setup.py install
script:
- pytest
after_success:
- echo $TRAVIS_SECURE_ENV_VARS
- coveralls